package jrm.server.shared.datasources;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import javax.xml.stream.XMLStreamException;

import jrm.misc.Log;
import jrm.profile.data.AnywareList;
import jrm.profile.data.MachineList;
import jrm.profile.data.MachineListList;
import jrm.server.shared.datasources.XMLRequest.Operation;
import jrm.xml.SimpleAttribute;

/**
 * Handles XML responses for retrieving a list of Anyware lists (e.g., MachineListList, SoftwareListList).
 * <p>
 * This class processes incoming XML requests to fetch metadata about available lists of ROMs or software. It supports optional
 * filtering by status and cache resetting.
 * </p>
 * <h2>XML Protocol</h2>
 * <ul>
 * <li><b>Incoming Request Parameters:</b>
 * <ul>
 * <li>{@code status}: (Optional) Comma-separated list of status strings to filter the lists.</li>
 * <li>{@code reset}: (Optional) Boolean flag indicating whether to reset the cache before fetching.</li>
 * </ul>
 * </li>
 * <li><b>Outgoing Response Structure:</b>
 * 
 * <pre>
 * <code class="language-xml">
 * &lt;response&gt;
 *   &lt;status&gt;0&lt;/status&gt;
 *   &lt;!-- Multiple record elements generated by fetchList --&gt;
 *   &lt;record status="..." name="..." description="..." have="..."/&gt;
 * &lt;/response&gt;
 *     </code>
 * </pre>
 * 
 * </li>
 * </ul>
 *
 * @author JRomManager Team
 * 
 * @see XMLResponse
 * @see XMLRequest.Operation
 */
public class AnywareListListXMLResponse extends XMLResponse {

    /**
     * The XML element name for the status indicator.
     */
    private static final String STATUS = "status";

    /**
     * Constructs a new AnywareListListXMLResponse for the given request.
     *
     * @param request The incoming XML request containing operation data.
     * 
     * @throws IOException If an I/O error occurs during response generation.
     * @throws XMLStreamException If an XML streaming error occurs.
     */
    public AnywareListListXMLResponse(XMLRequest request) throws IOException, XMLStreamException {
        super(request);
    }

    /**
     * Fetches the list of Anyware lists and writes them to the XML response.
     * <p>
     * If the {@code reset} parameter is true, the cache of the MachineListList is reset. The lists are then filtered based on the
     * {@code status} parameter, if provided.
     * </p>
     *
     * @param operation The operation containing request parameters.
     * 
     * @throws XMLStreamException If an XML streaming error occurs during writing.
     */
    @Override
    protected void fetch(Operation operation) throws XMLStreamException {
        writer.writeStartElement("response");
        writer.writeElement(STATUS, "0");
        final Set<String> lstatus = operation.hasData(STATUS) ? Stream.of(operation.getData(STATUS).split(",")).collect(Collectors.toSet()) : null;
        final var reset = Boolean.parseBoolean(operation.getData("reset"));
        final var mll = request.session.getCurrProfile().getMachineListList();
        if (mll != null) {
            if (reset)
                mll.resetCache();
            final List<AnywareList<?>> fll = new ArrayList<>();
            for (var i = 0; i < mll.count(); i++) {
                AnywareList<?> l = mll.getObject(i);
                if (lstatus == null || lstatus.contains(l.getStatus().toString()))
                    fll.add(l);
            }
            fetchList(operation, fll, (list, i) -> writeRecord(mll, list, i));
        }
        writer.writeEndElement();
    }

    /**
     * Writes a single record for an Anyware list to the XML response.
     *
     * @param mll The MachineListList containing the list.
     * @param list The AnywareList to write.
     * @param i The index of the list in the MachineListList.
     */
    private void writeRecord(final MachineListList mll, AnywareList<?> list, int i) {
        try {
            writer.writeElement("record", new SimpleAttribute(STATUS, list.getStatus()), new SimpleAttribute("name", list instanceof MachineList ? "*" : list.getBaseName()),
                    new SimpleAttribute("description", mll.getDescription(i)), new SimpleAttribute("have", mll.getHaveTot(i)));
        } catch (XMLStreamException e) {
            Log.err(e.getMessage(), e);
        }
    }
}