name: Beta Release

on: 
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+-beta.[0-9]+'

jobs:

  build_linux:
    runs-on: ubuntu-latest
    steps:
    
    - id: get_version
      uses: battila7/get-version-action@v2
      
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: Retain JDK 14 Path
      id: jdk14
      run: |
        echo "JDK14=${{env.JAVA_HOME}}" >> $GITHUB_ENV
        
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Releasing
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/distributions/JRomManager-*-src.tgz, JRomManager/build/distributions/jrommanager_*_*.deb, JRomManager/build/distributions/jrommanager-*.*.rpm, JRomManager/build/distributions/JRomManager-*.zip"
        draft: true
        prerelease: true
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        replacesArtifacts: true
        name: "v${{ steps.get_version.outputs.version }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: JPackage DEB with Gradle
      run: ./gradlew :JRomManager:jpackage -PtargetPlatform=linux-x64 -PinstallerType=deb
      env:
        JAVA_OPTS: -Dbadass.jlink.jpackage.home=${{env.JDK14}}
        
    - name: Releasing DEB
      uses: ncipollo/release-action@v1
      with:
        artifacts: "JRomManager/build/installer/*"
        draft: true
        prerelease: true
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: JPackage RPM with Gradle
      run: ./gradlew :JRomManager:jpackage -PtargetPlatform=linux-x64 -PinstallerType=rpm
      env:
        JAVA_OPTS: -Dbadass.jlink.jpackage.home=${{env.JDK14}}
        
    - name: Releasing RPM
      uses: ncipollo/release-action@v1
      with:
        artifacts: "JRomManager/build/installer/*"
        draft: true
        prerelease: true
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
  build_windows:
    needs: build_linux
    runs-on: windows-latest
    steps:
    
    - id: get_version
      uses: battila7/get-version-action@v2
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        
    - name: Retain JDK 14 Path
      id: jdk14
      run: |
        chcp 65001 #set code page to utf-8
        echo ("JDK14=" + $env:JAVA_HOME) >> $env:GITHUB_ENV
        
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: JPackage MSI with Gradle
      run: ./gradlew :JRomManager:jpackage -PtargetPlatform=win -PinstallerType=msi
      env:
        JAVA_OPTS: -Dbadass.jlink.jpackage.home=${{env.JDK14}}
        
    - name: Releasing MSI
      uses: ncipollo/release-action@v1
      with:
        artifacts: "JRomManager/build/installer/*"
        draft: true
        prerelease: true
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
        