name: Release

on: 
  push:
    tags:
    - '*'

jobs:

  build_linux:
    env:
      beta: ${{contains(github.ref, 'beta')}}
    runs-on: ubuntu-latest
    steps:
    
    - id: get_version
      uses: battila7/get-version-action@v2
      
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Set up JDK 14
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 14
        
    - name: Retain JDK 14 Path
      id: jdk14
      run: |
        echo "JDK14=${{env.JAVA_HOME}}" >> $GITHUB_ENV
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 17
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Releasing
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/distributions/jrommanager_*_*.deb, build/distributions/jrommanager-*.*.rpm, build/distributions/JRomManager-*.zip"
        draft: false
        prerelease: ${{ env.beta }}
        allowUpdates: true
        bodyFile: "changelogs/${{ steps.get_version.outputs.version }}.md"
        omitNameDuringUpdate: true
        replacesArtifacts: true
        name: "v${{ steps.get_version.outputs.version }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: JPackage DEB with Gradle
      run: ./gradlew jpackage -PtargetPlatform=linux-x64 -PinstallerType=deb
      env:
        JAVA_OPTS: -Dbadass.jlink.jpackage.home=${{env.JDK14}}
        
    - name: Releasing DEB
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/installer/*"
        draft: false
        prerelease: ${{ env.beta }}
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: JPackage RPM with Gradle
      run: ./gradlew jpackage -PtargetPlatform=linux-x64 -PinstallerType=rpm
      env:
        JAVA_OPTS: -Dbadass.jlink.jpackage.home=${{env.JDK14}}
        
    - name: Releasing RPM
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/installer/*"
        draft: false
        prerelease: ${{ env.beta }}
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: build AppImage
      run: ./appimage/build.sh
        
    - name: Releasing AppImage
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/JRomManager-*.AppImage"
        draft: false
        prerelease: ${{ env.beta }}
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
  build_windows:
    env:
      beta: ${{contains(github.ref, 'beta')}}
    needs: build_linux
    runs-on: windows-latest
    steps:
    
    - id: get_version
      uses: battila7/get-version-action@v2
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Set up JDK 14
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 14
        
    - name: Retain JDK 14 Path
      id: jdk14
      run: |
        chcp 65001 #set code page to utf-8
        echo ("JDK14=" + $env:JAVA_HOME) >> $env:GITHUB_ENV
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 17
        
    - name: JPackage MSI with Gradle
      run: ./gradlew jpackage -PtargetPlatform=win -PinstallerType=msi
      env:
        JAVA_OPTS: -Dbadass.jlink.jpackage.home=${{env.JDK14}}
        
    - name: Releasing MSI
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/installer/*"
        draft: false
        prerelease: ${{ env.beta }}
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
  build_macos:
    env:
      beta: ${{contains(github.ref, 'beta')}}
    needs: build_windows
    runs-on: macos-latest
    steps:
    
    - id: get_version
      uses: battila7/get-version-action@v2
    - uses: actions/checkout@v3
      with:
        submodules: true
        
    - name: Set up JDK 14
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 14
        
    - name: Retain JDK 14 Path
      id: jdk14
      run: |
        echo "JDK14=${{env.JAVA_HOME}}" >> $GITHUB_ENV
        
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 17
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: JPackage DMG with Gradle
      run: ./gradlew jpackage -PtargetPlatform=macos-x64 -PinstallerType=dmg
      env:
        JAVA_OPTS: -Dbadass.jlink.jpackage.home=${{env.JDK14}}
        
    - name: Releasing DMG
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/installer/*"
        draft: false
        prerelease: ${{ env.beta }}
        allowUpdates: true
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        
